# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ize1112 < Formula
  desc "IZE is an opinionated infrastructure wrapper that allows to use multiple tools in one infra"
  homepage "https://ize.sh/"
  version "1.1.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hazelops/ize/releases/download/1.1.12/ize_1.1.12_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "f391913377338aa94ef39840d2fd2ef070bee282d8f41cac56d40839b5ec4a10"

      def install
        bin.install "ize"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hazelops/ize/releases/download/1.1.12/ize_1.1.12_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "3bcced3373ebb22ea32240dd5be071b66dc4f198d22f483855e4f74b48fb5137"

      def install
        bin.install "ize"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hazelops/ize/releases/download/1.1.12/ize_1.1.12_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "5e41945ed8a1c8c25f916252d42c2f23ce1158563a08a56ba704379608cabb5d"

      def install
        bin.install "ize"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hazelops/ize/releases/download/1.1.12/ize_1.1.12_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "f4e945231053a8517283b2c633da01cfd7cafcf63ccfc4c42649204e98fdb06b"

      def install
        bin.install "ize"
      end
    end
  end

  conflicts_with "ize-dev"

  test do
    system "#{bin}/ize"
  end
end
