# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ize1113 < Formula
  desc "IZE is an opinionated infrastructure wrapper that allows to use multiple tools in one infra"
  homepage "https://ize.sh/"
  version "1.1.13"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hazelops/ize/releases/download/1.1.13/ize_1.1.13_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "839e7d2c99bde7e711a42193c894edd424459dcbdc86889cfc82fa1ac77553b1"

      def install
        bin.install "ize"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hazelops/ize/releases/download/1.1.13/ize_1.1.13_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "34a075312174ee6dc15b677c9e3aed9fed50bb4c225fb40b2137ffbf30664778"

      def install
        bin.install "ize"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hazelops/ize/releases/download/1.1.13/ize_1.1.13_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "553bad6a49e35bae2b72f6321dcff9965be12d725678b944b7290763c32f09dc"

        def install
          bin.install "ize"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hazelops/ize/releases/download/1.1.13/ize_1.1.13_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "fc304de9dd6fef1c0439fa724588ccbc9b9e931828c10a4fdb428a5bb811825e"

        def install
          bin.install "ize"
        end
      end
    end
  end

  conflicts_with "ize-dev"

  test do
    system "#{bin}/ize"
  end
end
