# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ize040 < Formula
  desc "IZE is an opinionated infrastructure wrapper that allows to use multiple tools in one infra"
  homepage "https://ize.sh/"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hazelops/ize/releases/download/0.4.0/ize_0.4.0_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "57b10434d72ff70e01a7380b7aedcd4b1663e155a498f2d8d6edd1eeb1035138"

      def install
        bin.install "ize"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hazelops/ize/releases/download/0.4.0/ize_0.4.0_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "aae9d2a5ea179dde79b7dfccf706e7d9b752875594bbe491655a94b7b7d5b72d"

      def install
        bin.install "ize"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hazelops/ize/releases/download/0.4.1/ize_0.4.0_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "41ad1befd1725c73be28356e56b78e0f56400ffbc15ce9246e213042879ad199"

      def install
        bin.install "ize"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hazelops/ize/releases/download/0.4.1/ize_0.4.0_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "56c36e2e8da40f0f6d4a541b7c5e946142b7de27cd10630f1820d0d95195d167"

      def install
        bin.install "ize"
      end
    end
  end

  conflicts_with "ize-dev"

  test do
    system "#{bin}/ize"
  end
end
