# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ize041 < Formula
  desc "IZE is an opinionated infrastructure wrapper that allows to use multiple tools in one infra"
  homepage "https://ize.sh/"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hazelops/ize/releases/download/0.4.1/ize_0.4.1_darwin_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "550f8230f3dbb7e184db828dbd328cc539c73f842b00491c23d30a834345984f"

      def install
        bin.install "ize"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hazelops/ize/releases/download/0.4.1/ize_0.4.1_darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "703eb5f73f8e561ba86ddbee397be480967b2852a0c097b98eedac63a9af8013"

      def install
        bin.install "ize"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hazelops/ize/releases/download/0.4.1/ize_0.4.1_linux_amd64.tar.gz", :using => CurlDownloadStrategy
      sha256 "e0be599c8e622edfe954e384bde6f88197b078942f3d8ddcd3c3aa6edb45de76"

      def install
        bin.install "ize"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hazelops/ize/releases/download/0.4.1/ize_0.4.1_linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "ef23ce80a1556026a7ae93328c8195a19944f97dcabec0d1c9d39eb8e7885b13"

      def install
        bin.install "ize"
      end
    end
  end

  conflicts_with "ize-dev"

  test do
    system "#{bin}/ize"
  end
end
