# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ize < Formula
  desc "IZE is an opinionated infrastructure wrapper that allows to use multiple tools in one infra"
  homepage "https://ize.sh/"
  version "1.1.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hazelops/ize/releases/download/1.1.9/ize_1.1.9_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "15400afc45e2a7ce6ba3b0503a4498a6967806ea3692d2c691ca2a613167aed2"

      def install
        bin.install "ize"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hazelops/ize/releases/download/1.1.9/ize_1.1.9_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "2f574cfd996b61c2f709f1e7fd3f31dfd9c86d186b0621c363d2bf0b7727354d"

      def install
        bin.install "ize"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hazelops/ize/releases/download/1.1.9/ize_1.1.9_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "8c4b7a6323d997c482850890ac87279f04768ca19fb3a4eecb06dd94f0d2a353"

      def install
        bin.install "ize"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hazelops/ize/releases/download/1.1.9/ize_1.1.9_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "cc58232972fc1e376c33736d91f026c7425c44fc8cc7cd10a5bf1197821d22c3"

      def install
        bin.install "ize"
      end
    end
  end

  conflicts_with "ize-dev"

  test do
    system "#{bin}/ize"
  end
end
